version: '3.8'

services:
  app:
    image: ghcr.io/gabrimartinss/ruby-trivia:latest
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://postgres:secret@db:5432/ruby_trivia_production
    depends_on:
      - db
    command: bash -c "rm -f /app/tmp/pids/server.pid && bin/rails db:prepare && bin/rails server -b 0.0.0.0"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ruby_trivia_production